// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rPKyjCTG0fexO3OKQGzKrLbrxbfj87s',
    appId: '1:503003668988:web:26758c7c3075e7bd349279',
    messagingSenderId: '503003668988',
    projectId: 'rozgarseek',
    authDomain: 'rozgarseek.firebaseapp.com',
    storageBucket: 'rozgarseek.firebasestorage.app',
    measurementId: 'G-19WKECWNEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwe3BFQi9T3LxrpYGc4yTtBdIWkRdnbKo',
    appId: '1:503003668988:android:28dbf6ddc4bb8558349279',
    messagingSenderId: '503003668988',
    projectId: 'rozgarseek',
    storageBucket: 'rozgarseek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvXvm1DrnwxTEJchOzEtju7bi89ZG1BcY',
    appId: '1:503003668988:ios:424f9c807d311ee5349279',
    messagingSenderId: '503003668988',
    projectId: 'rozgarseek',
    storageBucket: 'rozgarseek.firebasestorage.app',
    iosBundleId: 'com.example.razgorsek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvXvm1DrnwxTEJchOzEtju7bi89ZG1BcY',
    appId: '1:503003668988:ios:424f9c807d311ee5349279',
    messagingSenderId: '503003668988',
    projectId: 'rozgarseek',
    storageBucket: 'rozgarseek.firebasestorage.app',
    iosBundleId: 'com.example.razgorsek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2rPKyjCTG0fexO3OKQGzKrLbrxbfj87s',
    appId: '1:503003668988:web:d35e5c44168ba3f0349279',
    messagingSenderId: '503003668988',
    projectId: 'rozgarseek',
    authDomain: 'rozgarseek.firebaseapp.com',
    storageBucket: 'rozgarseek.firebasestorage.app',
    measurementId: 'G-24470EE09F',
  );
}
